create table if not exists public.drive_folder_cache (
  id bigint generated by default as identity primary key,
  parent_id text not null default '',
  folder_name text not null,
  folder_id text not null,
  last_verified_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists drive_folder_cache_parent_name_idx
  on public.drive_folder_cache (parent_id, folder_name);

create index if not exists drive_folder_cache_folder_id_idx
  on public.drive_folder_cache (folder_id);

create or replace function public.set_drive_folder_cache_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists drive_folder_cache_set_updated_at
  on public.drive_folder_cache;

create trigger drive_folder_cache_set_updated_at
before update on public.drive_folder_cache
for each row
execute function public.set_drive_folder_cache_updated_at();
