create table if not exists public.organizational_chart_entries (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('pasu', 'assistant_pasu', 'pamo_staff', 'former_pasu')),
  full_name text not null,
  position_title text not null,
  email text not null,
  mobile text not null,
  status text not null default 'active' check (
    status in ('active', 'archived', 'resigned', 'retired', 'end_of_contract', 'transferred', 'reassigned')
  ),
  notes text not null default '',
  attachment_path text,
  attachment_name text,
  attachment_size bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists organizational_chart_entries_single_active_pasu_idx
  on public.organizational_chart_entries (section)
  where section = 'pasu' and status = 'active';

create index if not exists organizational_chart_entries_section_status_idx
  on public.organizational_chart_entries (section, status, created_at desc);

create or replace function public.set_organizational_chart_entries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists organizational_chart_entries_set_updated_at
  on public.organizational_chart_entries;

create trigger organizational_chart_entries_set_updated_at
before update on public.organizational_chart_entries
for each row
execute function public.set_organizational_chart_entries_updated_at();
