create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_code text not null unique,
  contact_name text not null,
  contact_number text not null,
  email text,
  organization_name text,
  booking_type text not null,
  participant_category text not null,
  start_date date not null,
  end_date date not null,
  trail text not null,
  pax integer not null check (pax > 0 and pax <= 30),
  payment_status text not null,
  approval_status text not null,
  booking_status text not null,
  remarks text not null,
  internal_notes text,
  rescheduled_from text,
  cancel_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_date_range_chk check (end_date >= start_date)
);

create index if not exists bookings_trail_dates_idx
  on public.bookings (trail, start_date, end_date);

create index if not exists bookings_status_idx
  on public.bookings (approval_status, booking_status);
